version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fire-osint
    volumes:
      - database-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
            - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
volumes:
    database-data:
    pgadmin: